CMR-6899 - EDL Token support
nasa/eo-metadata-tools pull request #29
Opened 2021-04-20 18:29 UTC by jceaser

CMR-6899 : Adding documentation about using EDL tokens and allowed token file to have comments, added jupyter notebook test

The code was already working with the new EDL tokens but no documentation existing. Also added the ability to comment out tokens in the token file making it easy to have SIT, UAT, and OPS tokens all at once.

To try out this code and too see more information on it, try the token notebook.

2021-04-21 20:27 UTC, eereiter requested changes

2021-04-21 20:27 UTC, eereiter commented on CMR/python/cmr/auth/token.py
> +    Recursively calls lambdas till a token is found. These lamdba functions
Change the word Recursively to iterate through the list until a token is found. or something like that.

2021-04-21 20:27 UTC, eereiter commented on CMR/python/demos/notebooks/tokens.ipynb
>      "Just for this demo, I'm going to create a function that hids some of an EDL token, I don't want anyone to actually see my tokens"
misspelled hids  - should be hides.

2021-04-21 20:27 UTC, eereiter commented on CMR/python/demos/notebooks/tokens.ipynb
> +    "This will not be needed once we have the library working through PIP, but with this a local checkout can be used. In this case, the command `git clone https://github.com/nasa/eo-metadata-tools`
with this, (add comma)

2021-04-21 20:41 UTC, eereiter approved these changes

2021-04-22 13:41 UTC, mmorahan approved these changes
Looks good to me.

2021-04-22 13:45 UTC, merged