CMR-8863: Investigate graphDb operational issues
nasa/eo-metadata-tools pull request #54
Opened 2023-01-03 17:46 UTC by eudoroolivares2016

* Related to ticket, insofar as it is one of the scripts used for analysis to compare the collections on CMR to those in graphDb

* Running python graphqlPaging.py will write the concept-ids of all collections that you have access to according to your TOKEN. These will be printed to a local file collectionConceptIdList.txt

* A fairly minimal example for using python to call cmr-graphql and retrieve data

2023-01-04 16:44 UTC, jceaser requested changes
First priority, run pylint if you have not

2023-01-04 16:44 UTC, jceaser commented on CMR/python/graphql/graphqlPaging.py
> +}"""% (cursor)
does pylint complain about this older syntax? You use the modern "f" syntax on line 9 but not here. if pylint says nothing then your fine.

2023-01-04 16:44 UTC, jceaser commented on CMR/python/graphql/graphqlPaging.py
> +import json
no description of what this file does, normally I would not care, but you don't have a readme file in the same directory, so no one knows what this is about.

2023-01-04 16:44 UTC, jceaser commented on CMR/python/graphql/graphqlPaging.py
> +first_result = response.json()
your going to grab the response before you check the status code?

2023-01-04 16:44 UTC, jceaser commented on CMR/python/graphql/graphqlPaging.py
> +    with open("collectionConceptIdList.txt", "w") as txt_file:
so if you send all your debug statements to standard error, and your output to standard out, you can use pipes and not have to manage file stuff in the code, just an idea. You can just print out the arr values when you get them and not manage the array as well.

basically, all your current print lines could go to stand error, and what you want to go to the file should be standard out to simplify this. If you go down this path, the readme should show an example expected command line call.

2023-01-04 16:44 UTC, jceaser commented on CMR/python/graphql/graphqlPaging.py
> +    with open("collectionConceptIdList.txt", "w") as txt_file:
`print('Error message', file=sys.stderr)`

2023-02-08 20:21 UTC, closed without merging

2023-02-08 20:22 UTC, eudoroolivares2016 commented
It was suggested that this type of script could live on the future `graphql` landing page so I will close this PR